[workspace]
members = [
    "runtime/molt-runtime",
    "runtime/molt-obj-model",
    "runtime/molt-backend",
    "runtime/molt-db",
    "runtime/molt-worker",
    "runtime/molt-wasm-host",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
