[package]
name = "molt-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cranelift = "0.116"
cranelift-module = "0.116"
cranelift-object = "0.116"
cranelift-native = "0.116"
target-lexicon = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
molt-obj-model = { path = "../molt-obj-model" }
wasm-encoder = "0.32.0"
