[package]
name = "molt-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
molt_debug_gil = []

[dependencies]
molt-obj-model = { path = "../molt-obj-model" }
serde_json = "1.0"
rmpv = "1.0"
serde_cbor = "0.11"
crossbeam-deque = "0.8"
crossbeam-channel = "0.5"
num_cpus = "1.16"
lazy_static = "1.4"
memchr = "2.7"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
libc = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simdutf = "0.6"
getrandom = "0.2"
mio = { version = "0.8", features = ["os-poll", "net"] }
socket2 = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
